# Generated by Django 2.2.12 on 2020-05-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provider name (endesa, fenosa...)', max_length=64, verbose_name='Name')),
                ('host', models.CharField(help_text='Hostname or ip', max_length=64, verbose_name='Host')),
                ('port', models.PositiveIntegerField(help_text='Port to connect', verbose_name='Port')),
                ('username', models.CharField(help_text='User name of the connection', max_length=64, verbose_name='Username')),
                ('password', models.CharField(help_text='Password of the connection', max_length=128, verbose_name='Password')),
                ('base_dir', models.CharField(help_text='Base directory when start a connection', max_length=128, verbose_name='Base directory')),
                ('secure', models.BooleanField(default=True, help_text='Set if this connection will be secure or not, default true', verbose_name='Secure')),
                ('active', models.BooleanField(help_text='Check to enable or disable this provider', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Provider connection',
                'verbose_name_plural': 'Provider connections',
            },
        ),
        migrations.CreateModel(
            name='Curve2Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the curve (p1d, f5d....)', max_length=20, verbose_name='Name')),
                ('pattern', models.CharField(help_text='Pattern (python regex) of the curve file', max_length=255, null=True, verbose_name='Pattern')),
                ('active', models.BooleanField(help_text='Check to enable or disable exchange this kind of curves', verbose_name='Active')),
                ('last_upload', models.DateTimeField(blank=True, help_text='Last time this kind of curves was uploaded', null=True, verbose_name='Last date uploaded')),
                ('provider_connection', models.ForeignKey(help_text='Provider connection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curve2exchange', to='curves_exchange.ProviderConnection', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Curve to exchange',
                'verbose_name_plural': 'Curves to exchane',
            },
        ),
    ]
