# Generated by Django 2.1.4 on 2019-01-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somexchanger99', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file2exchange',
            name='model',
            field=models.CharField(help_text='Dotted model name in erp, eg. "giscedata.switching"', max_length=256, verbose_name='ERP model'),
        ),
        migrations.AlterField(
            model_name='file2exchange',
            name='process',
            field=models.CharField(help_text='ATR process (F1, A3, C1, ...)', max_length=128, verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='file2exchange',
            name='step',
            field=models.CharField(blank=True, help_text='Step of the ATR process. No used when process is F1', max_length=10, null=True, verbose_name='Step'),
        ),
    ]
