# Generated by Django 2.1.7 on 2019-02-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somexchanger99', '0002_auto_20190129_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='file2exchange',
            name='active',
            field=models.BooleanField(default=True, help_text='Shows if this kind of files will be exchanged', verbose_name='Active'),
            preserve_default=False,
        ),
    ]
