# Generated by Django 2.2.5 on 2019-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somexchanger99', '0003_file2exchange_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curve2Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the curve (p1d, f5d....)', max_length=20, verbose_name='Name')),
                ('active', models.BooleanField(help_text='Check to enable or disable exchange this kind of curves', verbose_name='Active')),
            ],
        ),
    ]
