# Generated by Django 2.2.5 on 2019-11-26 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somexchanger99', '0004_curve2exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='curve2exchange',
            name='last_upload',
            field=models.DateTimeField(blank=True, help_text='Last time this kind of curves was uploaded', null=True, verbose_name='Last date uploaded')
        ),
    ]
