# Generated by Django 2.2.5 on 2019-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somexchanger99', '0005_curve2exchange_last_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='curve2exchange',
            name='erp_name',
            field=models.CharField(help_text='Name of the curve in ERP (p1, f5d....)', max_length=20, null=True, verbose_name='ERP Name'),
        ),
    ]
