# Generated by Django 3.0 on 2019-12-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somexchanger99', '0006_curve2exchange_erp_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File2Exchange',
            new_name='Atr2Exchange',
        ),
    ]
