# Generated by Django 3.0 on 2019-12-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somexchanger99', '0007_auto_20191212_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='File2Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the curve (p1d, f5d....)', max_length=20, verbose_name='Name')),
                ('pattern', models.CharField(help_text='Pattern of the name to search the file. Has to be a python regex', max_length=20, null=True, verbose_name='Pattern')),
                ('active', models.BooleanField(help_text='Check to enable or disable exchange this kind of curves', verbose_name='Active')),
                ('last_upload', models.DateTimeField(blank=True, help_text='Last time this kind of curves was uploaded', null=True, verbose_name='Last date uploaded')),
            ],
        ),
    ]
