# Generated by Django 2.2.12 on 2020-05-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somexchanger99', '0010_auto_20200507_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curve2Exchange',
        ),
    ]
