# Generated by Django 4.1.7 on 2023-03-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somexchanger99', '0011_curve2exchange_pattern'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atr2exchange',
            options={'verbose_name': 'atr to exchange', 'verbose_name_plural': 'atrs to exchange'},
        ),
        migrations.AlterModelOptions(
            name='curve2exchange',
            options={'verbose_name': 'curve to exchange', 'verbose_name_plural': 'curves to exchange'},
        ),
        migrations.AlterModelOptions(
            name='file2exchange',
            options={'verbose_name': 'file to exchange', 'verbose_name_plural': 'files to exchange'},
        ),
        migrations.AlterField(
            model_name='atr2exchange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='curve2exchange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file2exchange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='originfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
